"""Route metadata for read-only system API endpoints."""

from __future__ import annotations


ROUTE_SPECS_SYSTEM = [
    ("GET", "/api/system/kill_switches", "api_get_kill_switches"),
    ("GET", "/api/system/state", "api_get_system_state"),
    ("GET", "/api/system/health", "api_get_health"),
    ("GET", "/api/system/liveness", "api_get_liveness"),
    ("GET", "/api/system/competition", "api_get_competition_view"),
    ("GET", "/api/system/replay_freshness", "api_get_replay_freshness"),
    ("GET", "/api/system/attribution_quality", "api_get_attribution_quality"),
    ("GET", "/api/system/mode", "api_get_status"),
    ("GET", "/api/system/config", "api_get_runtime_config"),
    ("GET", "/api/supervisor/status", "api_get_supervisor_status"),
    ("GET", "/api/ingestion/status", "api_get_ingestion_status"),
    ("GET", "/api/health", "api_get_health"),
    ("GET", "/api/liveness", "api_get_liveness"),
    ("GET", "/api/status", "api_get_status"),
    ("GET", "/api/readiness", "api_get_readiness"),
    ("GET", "/api/readiness/evidence", "api_get_readiness_evidence"),
    ("GET", "/api/system/readiness_evidence", "api_get_readiness_evidence"),
    ("GET", "/api/system/trading_readiness", "api_get_trading_readiness"),
    ("GET", "/api/operator/readiness_evidence", "api_get_readiness_evidence"),
    ("GET", "/api/operator/trading_readiness", "api_get_trading_readiness"),
    ("GET", "/api/operator/preflight_report", "api_get_preflight_report"),
    ("GET", "/api/operator/runtime_watchdogs", "api_get_runtime_watchdogs"),
    ("GET", "/api/operator/service_status", "api_get_service_status"),
    ("GET", "/api/operator/support_snapshot", "api_get_support_snapshot"),
    ("GET", "/api/operator/snapshot", "api_get_support_snapshot"),
    ("GET", "/api/operator/competition", "api_get_competition_view"),
    ("GET", "/api/operator/replay_freshness", "api_get_replay_freshness"),
    ("GET", "/api/operator/attribution_quality", "api_get_attribution_quality"),
    ("GET", "/api/operator/provider_telemetry", "api_get_provider_telemetry"),
    ("GET", "/api/operator/supervisor_diagnostics", "api_get_supervisor_diagnostics"),
    ("GET", "/api/telemetry", "api_get_telemetry"),
    ("GET", "/api/telemetry/history", "api_get_telemetry_history"),
    ("GET", "/api/execution/barrier", "api_get_execution_barrier"),
    ("GET", "/api/risk/portfolio", "api_get_portfolio_risk"),
    ("GET", "/api/risk/monte_carlo", "api_get_monte_carlo_risk"),
    ("GET", "/api/alpha_decay", "api_get_alpha_decay"),
    ("GET", "/api/regime/context", "api_get_regime_context"),
    ("GET", "/api/regime/history", "api_get_regime_history"),
    ("GET", "/api/drift/explainer", "api_get_drift_explainer"),
    ("GET", "/api/allocator/status", "api_get_allocator_status"),
    ("GET", "/api/training_status", "api_get_training_status"),
    ("GET", "/api/server/status", "api_get_server_status"),
    ("POST", "/api/server/shutdown", "api_post_server_shutdown"),
]
