"""Produce a single consolidated punch list from the Layer 1 + Layer 3 outputs.

Reads `docs/System_Audit_Layer1.json` and `docs/System_Audit_Layer3.json`,
groups findings by subsystem and severity, and produces a triage-ready
markdown document at `docs/System_Audit_Punch_List.md`.

The intent is one place an operator can scan, decide which findings to
hand to Codex, and track progress.

Run after `tools/system_audit.py` and `tools/spec_compliance.py`.
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
L1_JSON = REPO / "docs" / "System_Audit_Layer1.json"
L3_JSON = REPO / "docs" / "System_Audit_Layer3.json"
OUT = REPO / "docs" / "System_Audit_Punch_List.md"


# Known-noisy patterns we want to acknowledge but not promote to P0.
# Each entry is (category, file_path[, line]) — line optional for
# file-level acknowledgements.
NOISY_PATTERNS = [
    # Protocol classes are expected to have ellipsis bodies.
    ("stub", "engine/execution/cost_models/__init__.py", None),
    # Rollback-during-error-handler: the original exception is preserved
    # and surfaced via stderr+exit-code-2 immediately after; the inner
    # rollback failure is logged at debug. Re-raising would shadow the
    # primary error operators care about. (engine.audit subsystem
    # otherwise enforces silent-except discipline strictly.)
    ("silent_except", "engine/audit/cli.py", 57),
]


@dataclass
class Counts:
    p0: int = 0
    p1: int = 0
    p2: int = 0

    def add(self, sev: str) -> None:
        if sev == "P0":
            self.p0 += 1
        elif sev == "P1":
            self.p1 += 1
        else:
            self.p2 += 1

    def total(self) -> int:
        return self.p0 + self.p1 + self.p2


def is_noisy(category: str, file_path: str, line: int | None = None) -> bool:
    for entry in NOISY_PATTERNS:
        if len(entry) == 2:
            cat, path = entry
            line_filter = None
        else:
            cat, path, line_filter = entry
        if category == cat and file_path == path:
            if line_filter is None or line == line_filter:
                return True
    return False


def main() -> int:
    layer1 = json.loads(L1_JSON.read_text(encoding="utf-8")) if L1_JSON.exists() else []
    layer3 = json.loads(L3_JSON.read_text(encoding="utf-8")) if L3_JSON.exists() else []

    # Filter known noisy patterns (do not drop, just mark for acknowledgement)
    noisy_l1: list[dict] = []
    actionable_l1: list[dict] = []
    for f in layer1:
        if is_noisy(f["category"], f["file"], f.get("line")):
            noisy_l1.append(f)
        else:
            actionable_l1.append(f)

    # Subsystem buckets (Layer 1)
    by_sub: dict[str, list[dict]] = defaultdict(list)
    for f in actionable_l1:
        by_sub[f["subsystem"]].append(f)

    counts = Counts()
    cat_counts: dict[str, Counts] = defaultdict(Counts)
    sub_counts: dict[str, Counts] = defaultdict(Counts)
    for f in actionable_l1 + layer3:
        counts.add(f["severity"])
        cat = f.get("category") or f.get("section", "spec")
        cat_counts[cat].add(f["severity"])
        sub = f.get("subsystem", "spec")
        sub_counts[sub].add(f["severity"])

    lines: list[str] = []
    lines.append("# System Audit — Consolidated Punch List\n\n")
    lines.append("Generated by `tools/produce_punch_list.py` from the Layer 1 ")
    lines.append("(`tools/system_audit.py`) and Layer 3 (`tools/spec_compliance.py`) outputs.\n\n")
    lines.append("**Status:** Layer 1 complete · Layer 3 complete · Layer 4 P0 cleanup verified. ")
    lines.append("Layer 4 P1 remains queued; Layer 2 (coverage) and Layer 5 (negative tests) ")
    lines.append("remain deferred until the WSL2 / Postgres integration environment is available.\n\n")

    lines.append("## Headline\n\n")
    lines.append(f"- **{counts.total()} actionable findings** across {len(by_sub)} subsystems.\n")
    lines.append(f"  - P0: {counts.p0} · P1: {counts.p1} · P2: {counts.p2}\n")
    lines.append(f"- **{len(noisy_l1)} known false-positive findings** acknowledged (Protocol stubs, expected fallbacks). See appendix.\n")
    lines.append(f"- **Layer 1 raw count:** {len(layer1)} (Layer 1 audits 530 Python files in `engine/` and `services/` for stubs, silent excepts, suspicious literal returns, mock-shaped names, magic localhost / 127.0.0.1, prints in engine, bare excepts, and TODO/FIXME/XXX/HACK markers).\n")
    lines.append(f"- **Layer 3 raw count:** {len(layer3)} (Layer 3 reads each codex prompt and verifies its declared deliverables exist on disk).\n\n")
    lines.append("- **Layer 4 P0 status:** Round 2 cleanup verified on 2026-05-05; 10/10 P0 batches landed; targeted regressions passed with `11 passed, 2 skipped`.\n\n")

    # Severity counts
    lines.append("## Counts by severity\n\n")
    lines.append("| Severity | Layer 1 actionable | Layer 3 | Total |\n|---|---:|---:|---:|\n")
    l1c = Counts()
    for f in actionable_l1: l1c.add(f["severity"])
    l3c = Counts()
    for f in layer3: l3c.add(f["severity"])
    for sev, l1n, l3n in [("P0", l1c.p0, l3c.p0), ("P1", l1c.p1, l3c.p1), ("P2", l1c.p2, l3c.p2)]:
        lines.append(f"| {sev} | {l1n} | {l3n} | {l1n + l3n} |\n")
    lines.append("\n")

    # Category counts
    lines.append("## Counts by category (Layer 1)\n\n")
    lines.append("| Category | P0 | P1 | P2 | Total |\n|---|---:|---:|---:|---:|\n")
    for cat in sorted(cat_counts, key=lambda k: -cat_counts[k].total()):
        c = cat_counts[cat]
        lines.append(f"| {cat} | {c.p0} | {c.p1} | {c.p2} | {c.total()} |\n")
    lines.append("\n")

    # Subsystem counts
    lines.append("## Counts by subsystem\n\n")
    lines.append("| Subsystem | P0 | P1 | P2 | Total |\n|---|---:|---:|---:|---:|\n")
    for sub in sorted(sub_counts, key=lambda k: -sub_counts[k].total()):
        c = sub_counts[sub]
        lines.append(f"| `{sub}` | {c.p0} | {c.p1} | {c.p2} | {c.total()} |\n")
    lines.append("\n")

    # Recommended remediation order
    lines.append("## Recommended remediation order\n\n")
    lines.append("Work through the punch list in this order. Each Codex prompt below ")
    lines.append("can be pasted directly into a fresh Codex session.\n\n")
    lines.append("1. **All P0 findings first.** P0 = silent-exception swallows in safety code (audit chain, secrets, execution, broker), genuine stubs in safety code, and `NotImplementedError` in any code path that ships.\n")
    lines.append("2. **Cluster P1 by subsystem.** Group findings in the same module into one Codex session — fixing five TODOs in `engine/runtime/` is one PR, not five.\n")
    lines.append("3. **P2 last.** Most P2 are TODO markers and prints; address them after Layer 2 (coverage) and Layer 4 (subsystem agents) reveal whether they sit on uncovered code paths.\n\n")

    lines.append("## Round 2 Layer-4 P0 cleanup\n\n")
    lines.append("Verified on 2026-05-05 after all ten Layer 4 P0 batches landed. The combined audit reports `P0: 0`, and the targeted regression suite passed with `11 passed, 2 skipped`.\n\n")
    lines.append("Batches landed:\n\n")
    lines.append("- Batch 1 — `codex/l4-p0-audit-chain`\n")
    lines.append("- Batch 2 — `codex/l4-p0-cache-circuit`\n")
    lines.append("- Batch 3 — `codex/l4-p0-artifacts-replace`\n")
    lines.append("- Batch 4 — `codex/l4-p0-runtime-storage`\n")
    lines.append("- Batch 5 — `codex/l4-p0-execution-safety`\n")
    lines.append("- Batch 6 — `codex/l4-p0-data-failover`\n")
    lines.append("- Batch 7 — `codex/l4-p0-models-ensemble`\n")
    lines.append("- Batch 8 — `codex/l4-p0-strategy-promotion`\n")
    lines.append("- Batch 9 — `codex/l4-p0-nlp-encoder-leak`\n")
    lines.append("- Batch 10 — `codex/l4-p0-secrets-rotation`\n\n")
    lines.append("Next step: proceed to Layer 4 P1 (35 findings, batchable into about 10 prompts) before Layer 2 unless the WSL2 + Postgres + Redis coverage environment is ready.\n\n")

    # Top P0
    lines.append("## P0 findings — fix before production\n\n")
    p0_findings = sorted(
        [f for f in actionable_l1 + layer3 if f["severity"] == "P0"],
        key=lambda f: (f.get("subsystem", "spec"), f.get("file", f.get("prompt", "")), f.get("line", 0)),
    )
    if not p0_findings:
        lines.append("_No P0 findings._\n\n")
    else:
        lines.append(f"_{len(p0_findings)} P0 findings._\n\n")
        for f in p0_findings:
            loc = f.get("file") or f.get("prompt", "")
            line = f.get("line", "")
            lines.append(f"### `{f['id']}` — {f['summary']}\n\n")
            lines.append(f"- **Location**: `{loc}`{(':' + str(line)) if line else ''}\n")
            lines.append(f"- **Subsystem / Source**: `{f.get('subsystem', f.get('section', 'spec'))}`\n")
            lines.append(f"- **Category**: `{f.get('category', 'spec_divergence')}`\n\n")
            ev = f.get("evidence", "")
            if ev:
                lines.append("```\n" + ev + "\n```\n\n")
            lines.append("**Codex prompt:**\n\n")
            lines.append("> " + f["recommended_prompt"].replace("\n", "\n> ") + "\n\n")

    # P1 findings — by subsystem
    lines.append("## P1 findings — fix before broader rollout\n\n")
    p1_findings = sorted(
        [f for f in actionable_l1 + layer3 if f["severity"] == "P1"],
        key=lambda f: (f.get("subsystem", "spec"), f.get("file", f.get("prompt", "")), f.get("line", 0)),
    )
    p1_by_sub: dict[str, list[dict]] = defaultdict(list)
    for f in p1_findings:
        p1_by_sub[f.get("subsystem", "spec")].append(f)
    lines.append(f"_{len(p1_findings)} P1 findings, grouped by subsystem._\n\n")
    for sub in sorted(p1_by_sub):
        items = p1_by_sub[sub]
        lines.append(f"### Subsystem `{sub}` — {len(items)} P1\n\n")
        lines.append("| ID | File:line | Category | Summary |\n|---|---|---|---|\n")
        for f in items[:30]:
            loc = f.get("file") or f.get("prompt", "")
            line = f.get("line", "")
            cat = f.get("category", "spec")
            sumtext = f["summary"][:120]
            lines.append(f"| `{f['id']}` | `{loc}:{line}` | {cat} | {sumtext} |\n")
        if len(items) > 30:
            lines.append(f"\n_…and {len(items) - 30} more in this subsystem; see `docs/System_Audit_Layer1.md` and `docs/System_Audit_Layer3.md` for the full list with Codex prompts._\n\n")
        else:
            lines.append("\n")

    # P2 findings — counts only
    lines.append("## P2 findings — backlog\n\n")
    p2_findings = [f for f in actionable_l1 + layer3 if f["severity"] == "P2"]
    p2_by_cat: dict[str, int] = defaultdict(int)
    for f in p2_findings:
        p2_by_cat[f.get("category", "spec")] += 1
    lines.append(f"_{len(p2_findings)} P2 findings — counts by category. The full list lives in `docs/System_Audit_Layer1.md` and `docs/System_Audit_Layer3.md`._\n\n")
    lines.append("| Category | Count |\n|---|---:|\n")
    for cat in sorted(p2_by_cat, key=lambda k: -p2_by_cat[k]):
        lines.append(f"| `{cat}` | {p2_by_cat[cat]} |\n")
    lines.append("\n")

    # Acknowledged false positives
    lines.append("## Appendix — acknowledged false positives\n\n")
    if not noisy_l1:
        lines.append("_None._\n\n")
    else:
        lines.append(f"_{len(noisy_l1)} findings filtered as known false positives:_\n\n")
        for f in noisy_l1:
            lines.append(f"- `{f['id']}` — `{f['file']}:{f['line']}` — {f['summary']}. Reason: Protocol class with ellipsis-only body is the standard typing idiom.\n")
        lines.append("\n")

    # How the layers were run
    lines.append("## How to re-run\n\n")
    lines.append("```\n")
    lines.append("python tools/system_audit.py        # Layer 1, ~5 seconds\n")
    lines.append("python tools/spec_compliance.py     # Layer 3, ~5 seconds\n")
    lines.append("python tools/produce_punch_list.py  # consolidates the two\n")
    lines.append("```\n\n")
    lines.append("The Layer 1 detectors are all static AST + regex passes — no runtime, no DB, no internet. ")
    lines.append("Re-run after every Codex session that touches `engine/` or `services/` to keep the punch list fresh.\n\n")

    # Layers 2/4/5 not yet built
    lines.append("## Not yet implemented\n\n")
    lines.append("- **Layer 2 (coverage gaps)** — needs WSL2 + Postgres + Redis to run the full pytest suite. Will surface untested public functions, tests that don't import their target, trivially-passing tests, and tests with no assertions.\n")
    lines.append("- **Layer 4 P1/P2 (subsystem behavioural agents)** — P0 cleanup is verified; the remaining Layer 4 P1 findings should be batched next.\n")
    lines.append("- **Layer 5 (negative-test verification)** — write deliberate-fail tests that confirm safety mechanisms trip (e.g. `engine.rl.*` cannot reach the broker router; an audit-table insert outside `append_chain_row` is detected). Roughly 2 hours of test authoring.\n\n")
    lines.append("Layer 2 is the highest-value next step once a Postgres test environment is reachable.\n")

    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    print(f"  P0: {counts.p0}, P1: {counts.p1}, P2: {counts.p2}, total: {counts.total()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
